AWSTemplateFormatVersion: 2010-09-09

Parameters:
  TemplateBucketName:
    Type: String
    Default: jujy-ecs
    
  Prefix:
    Type: String
    Default: ju
    
  HTTPPort:
    Type: Number
    Default: 80
    
  HTTPSPort:
    Type: Number
    Default: 443
    
  TaskCpu:
    Type: Number
    Default: 512
    
  TaskMemory:
    Type: Number
    Default: 1024


Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://jujy-ecs.s3.ap-northeast-2.amazonaws.com/vpc.yml
      Parameters:
        AvailabilityZone1: a
        AvailabilityZone2: b
        CidrIp1: 10.0.1.0/24
        CidrIp2: 10.0.2.0/24
        HTTPPort: !Ref HTTPPort
        Prefix: !Ref Prefix
        VPCCidrBlock: 10.0.0.0/16

  FargateStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
    Properties:
      TemplateURL: https://jujy-ecs.s3.ap-northeast-2.amazonaws.com/ecsFargate.yml
      Parameters:
        ContainerSecurityGroup: !GetAtt VPCStack.Outputs.ContainerSecurityGroup
        Prefix: !Ref Prefix
        PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2
        RepositoryName: "ju-ecr"
        TaskCpu: !Ref TaskCpu
        TaskMemory: !Ref TaskMemory