variable "tag" {}
variable "codecommit_http_url" {}
variable "log_resource" {}
variable "logs_actions" {}
variable "s3_resource" {}
variable "s3_actions" {}
variable "codecommit_resource" {}
variable "codecommit_actions" {}
variable "codebuild_resource" {}
variable "codebuild_actions" {}
variable "account_id" {}
variable "user_name" {}
variable "repo_name" {}
